#!/bin/bash -u
{ set +x; } 2>/dev/null
SOURCE=$0
DIR="$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )"
ROOTDIR=$(cd $DIR && cd ../ && pwd)

if [[ "$(uname)" = "Darwin" ]]; then
    OS="Mac"
elif [[ -e "/c/" ]]; then
    OS="Windows"
else
    OS="Linux"
fi

if [[ x"$OS" == x"Mac" ]]; then
    if which brew > /dev/null
    then
        echo "brew is installed, skipping…"
    else
        /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    fi

    brew tap azure/functions
    brew list azure-functions-core-tools@3 || brew install azure-functions-core-tools@3
fi

python3 -m venv .venv
source .venv/bin/activate

echo "Updating pip…"
python3 -m pip install --upgrade pip

echo "Installing dependencies…"
python3 -m pip install -r src/requirements.dev.txt