#!/bin/sh

echo @"
   _____ ___.  ___.           __   
  /  _  \\_ |__\_ |__   _____/  |_ 
 /  /_\  \| __ \| __ \ /  _ \   __\
/    |    \ \_\ \ \_\ (  <_> )  |  
\____|__  /___  /___  /\____/|__|  
        \/    \/    \/             
";
echo "";
echo "This script will setup dependencies necessary to develop Abbot on a Mac."
echo "It will ensure that brew, azure/functions, and azurite are installed."
echo "It will create a virtual environment for the Python function runner."
echo "It will also make sure your system has the correct development client secrets configured."
echo "If anything is installed or set, it won't try to install them again."
echo "If you don't want to continue, just hit Enter at the prompt."
echo "Otherwise, hit 'y' and then Enter to continue."
echo ""

read -p 'Continue? (y + Enter to continue, or anything else + Enter to stop):' toContinue

if [[ $toContinue != "Y" && $toContinue != "y" ]]; then
    echo "No problem, perhaps you want to install all this manually. No hard feelings."
    echo "Done!"
    exit 0
fi

if which brew > /dev/null
then
    echo "brew is installed, skipping…"
else
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

brew tap azure/functions
brew list azure-functions-core-tools@3 || brew install azure-functions-core-tools@3

if which azurite > /dev/null
then
    echo "azurite is installed, skipping…"
else
    npm i -g "azurite@latest"
fi

python3 -m venv src/env
source src/env/bin/activate
python3 -m pip install -r src/requirements.txt

echo "And we're back to where it all started."
echo "Done!"
