#!/bin/bash -u
{ set +x; } 2>/dev/null
SOURCE=$0
DIR="$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )"
ROOTDIR=$(cd $DIR && cd ../ && pwd)

if [[ "$(uname)" = "Darwin" ]]; then
    OS="Mac"
elif [[ -e "/c/" ]]; then
    OS="Windows"
else
    OS="Linux"
fi

cd "$ROOTDIR"

source src/env/bin/activate

func start --script-root src --port 7072
