name: Add Issue/PR To Project

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  add-issue-to-project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: GitHub App token
        id: generate_token
        uses: tibdex/github-app-token@v1.5.0
        with:
          app_id: ${{ secrets.SERIOUS_APP_ID }}
          private_key: ${{ secrets.SERIOUS_APP_KEY }}
      - uses: aseriousbiz/issue-actions/add-issue-to-project
        with:
          project: https://github.com/orgs/aseriousbiz/projects/1
          token: ${{ steps.generate_token.outputs.token }}