name: Container Python

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Custom image tag'
        required: false
        default: ''
      deploy:
        description: Trigger deployment
        required: false
        default: '0'
      publish:
        description: Trigger publish to orgs
        required: false
        default: '0'

  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  # Make sure images are built at least once a week.
  schedule:
    # https://crontab.guru/#22_16_*_*_1
    # "At 16:22 UTC (09:22 PT) every Monday"
    # GitHub recommends avoiding the top of the hour because it's commonly used by other actions.
    # Scheduled actions may be skipped if there's high load.
    - cron: '22 16 * * 1'

env:
  APP_NAME: abbot-skills-python
  LATEST_TAG: latest
  RUNNER: python

jobs:
  container:
    runs-on: ubuntu-latest

    steps:
    - name: Parse inputs
      if: ${{ github.event_name == 'workflow_dispatch' }}
      uses: actions-ecosystem/action-regex-match@v2
      id: parse_input
      with:
        text: ${{ github.event.inputs.tag }}
        regex: '^[\w\.-]+$'

    - run: echo "CUSTOM_TAG=${{steps.parse_input.outputs.match}}" >> $GITHUB_ENV
      if: ${{ github.event_name == 'workflow_dispatch' }}
    - run: echo "THETAG=${{env.LATEST_TAG}}" >> $GITHUB_ENV
      if: ${{ github.ref == 'refs/heads/main' }}
    - run: echo "THETAG=${{env.CANARY_TAG}}" >> $GITHUB_ENV
      if: ${{ github.ref == 'refs/heads/canary' }}
    - run: echo "THETAG=${{env.CUSTOM_TAG}}" >> $GITHUB_ENV
      if: ${{ github.event_name == 'workflow_dispatch' && env.CUSTOM_TAG != '' }}
    - run: echo "DEPLOY=1" >> $GITHUB_ENV
      if: (github.event.inputs.deploy == '1' && env.CUSTOM_TAG != '') || ((github.event_name == 'push' || github.event_name == 'schedule') && env.THETAG != '')
    - run: echo "PUBLISH=1" >> $GITHUB_ENV
      if: (github.event.inputs.publish == '1' && env.CUSTOM_TAG != '') || ((github.event_name == 'push' || github.event_name == 'schedule') && env.THETAG != '')

    - name: Checkout branch
      uses: actions/checkout@v3.1.0

    - name: Run Security Update Audit
      run: |
        script/audit

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: '{ "clientId": "${{ secrets.DEPLOYBOT_AZURE_AD_CLIENT_ID }}", "clientSecret": "${{ secrets.DEPLOYBOT_AZURE_AD_CLIENT_SECRET }}", "subscriptionId": "${{ secrets.AZURE_SUBSCRIPTION_ID }}", "tenantId": "${{ secrets.AZURE_TENANT_ID }}" }'

    - name: Login to abbotacr02.azurecr.io
      run: |
        az acr login -n abbotacr02 -g container-registry

    - name: Build ${{env.THETAG}}
      if: env.THETAG != ''
      run: |
        docker build --target build -t ${{ secrets.AZURE_ACR_SERVER }}/${{ env.APP_NAME }}-build:${{ env.THETAG }} -f docker/${{ env.APP_NAME }}.Dockerfile .
        docker build -t ${{ secrets.AZURE_ACR_SERVER }}/${{ env.APP_NAME }}:${{ env.THETAG }} -f docker/${{ env.APP_NAME }}.Dockerfile .
        docker push ${{ secrets.AZURE_ACR_SERVER }}/${{ env.APP_NAME }}-build:${{ env.THETAG }}
        docker push ${{ secrets.AZURE_ACR_SERVER }}/${{ env.APP_NAME }}:${{ env.THETAG }}

    - name: GitHub App token
      if: env.PUBLISH == 1 || env.DEPLOY == 1
      id: generate_token
      uses: tibdex/github-app-token@v1.7.0
      with:
        app_id: ${{ secrets.SERIOUSBOT_APPID }}
        private_key: ${{ secrets.SERIOUSBOT_KEY }}
        repository: "aseriousbiz/docker"

    - name: Publish ${{ env.THETAG }} containers to all orgs
      if: env.PUBLISH == 1
      env:
        GH_BOT_TOKEN: ${{ steps.generate_token.outputs.token }}
      run: |
        ./.github/registry_publish.sh ${{env.RUNNER}} ${{ env.THETAG }} ${{ env.THETAG }}

    - name: Deploy ${{ env.THETAG }} to fly
      if: env.DEPLOY == 1
      env:
        GH_BOT_TOKEN: ${{ steps.generate_token.outputs.token }}
      run: |
        ./.github/deploy_fly.sh ${{env.RUNNER}} ${{ env.THETAG }}
