name: Container Python

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Custom image tag'
        required: false
        default: ''
      deploy:
        description: Trigger deployment
        required: false
        default: '0'
      publish:
        description: Trigger publish to orgs
        required: false
        default: '0'

  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'docker/abbot-skills-python.Dockerfile'
      - '.github/*.sh'
      - '.github/workflows/main_abbot.yml'

env:
  APP_NAME: abbot-skills-python
  LATEST_TAG: latest
  RUNNER: python

jobs:
  container:
    runs-on: ubuntu-latest

    steps:
    - name: Parse inputs
      if: ${{ github.event_name == 'workflow_dispatch' }}
      uses: actions-ecosystem/action-regex-match@v2
      id: parse_input
      with:
        text: ${{ github.event.inputs.tag }}
        regex: '^[\w\.-]+$'

    - run: echo "CUSTOM_TAG=${{steps.parse_input.outputs.match}}" >> $GITHUB_ENV
      if: ${{ github.event_name == 'workflow_dispatch' }}
    - run: echo "THETAG=${{env.LATEST_TAG}}" >> $GITHUB_ENV
      if: ${{ github.ref == 'refs/heads/main' }}
    - run: echo "THETAG=${{env.CANARY_TAG}}" >> $GITHUB_ENV
      if: ${{ github.ref == 'refs/heads/canary' }}
    - run: echo "THETAG=${{env.CUSTOM_TAG}}" >> $GITHUB_ENV
      if: ${{ github.event_name == 'workflow_dispatch' && env.CUSTOM_TAG != '' }}
    - run: echo "DEPLOY=1" >> $GITHUB_ENV
      if: (github.event.inputs.deploy == '1' && env.CUSTOM_TAG != '') || (github.event_name != 'workflow_dispatch' && env.THETAG != '')
    - run: echo "PUBLISH=1" >> $GITHUB_ENV
      if: (github.event.inputs.publish == '1' && env.CUSTOM_TAG != '') || (github.event_name != 'workflow_dispatch' && env.THETAG != '')

    - name: Checkout branch
      uses: actions/checkout@v2

    - name: Login to docker
      uses: docker/login-action@v1
      with:
        registry: ${{ secrets.AZURE_ACR_SERVER }}
        username: ${{ secrets.AZURE_ACR_USER_CLIENTID }}
        password: ${{ secrets.AZURE_ACR_USER_CLIENTSECRET }}

    - name: Build ${{env.THETAG}}
      if: env.THETAG != ''
      run: |
        docker build -t ${{ secrets.AZURE_ACR_SERVER }}/${{ env.APP_NAME }}:${{ env.THETAG }} -f docker/${{ env.APP_NAME }}.Dockerfile .
        docker push ${{ secrets.AZURE_ACR_SERVER }}/${{ env.APP_NAME }}:${{ env.THETAG }}

    - name: Publish ${{ env.THETAG }} containers to all orgs
      if: env.PUBLISH == 1
      env:
        GH_BOT_TOKEN: ${{ secrets.GH_BOT_TOKEN }}
      run: |
        ./.github/registry_publish.sh ${{env.RUNNER}} ${{ env.THETAG }} ${{ env.THETAG }}

    - name: Deploy ${{ env.THETAG }} to fly
      if: env.DEPLOY == 1
      env:
        GH_BOT_TOKEN: ${{ secrets.GH_BOT_TOKEN }}
      run: |
        ./.github/deploy_fly.sh ${{env.RUNNER}} ${{ env.THETAG }}
