name: Container Python

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Custom image tag'
        required: false
        default: ''
  push:
    branches:
      - main
    paths:
      - src/
      - docker/*.Dockerfile

env:
  APP_NAME: abbot-skills-python
  LATEST_TAG: latest

jobs:
  container:
    runs-on: ubuntu-latest

    steps:
    - name: Parse inputs
      if: ${{ github.event_name == 'workflow_dispatch' }}
      uses: actions-ecosystem/action-regex-match@v2
      id: parse_input
      with:
        text: ${{ github.event.inputs.tag }}
        regex: '^[\w\.-]+$'

    - name: Checkout branch
      uses: actions/checkout@v2

    - name: Build image
      run: docker build -t ${{ secrets.AZURE_ACR_SERVER }}/${{ env.APP_NAME }}:${{ github.sha }} -f docker/${{ env.APP_NAME }}.Dockerfile .

    - name: Tag latest on main
      if: ${{ github.ref == 'refs/heads/main' }}
      run: docker image tag ${{ secrets.AZURE_ACR_SERVER }}/${{ env.APP_NAME }}:${{ github.sha }} ${{ secrets.AZURE_ACR_SERVER }}/${{ env.APP_NAME }}:${{ env.LATEST_TAG }}

    - name: Custom tag
      if: ${{ github.event_name == 'workflow_dispatch' && steps.parse_input.outputs.match != '' }}
      run: docker image tag ${{ secrets.AZURE_ACR_SERVER }}/${{ env.APP_NAME }}:${{ github.sha }} ${{ secrets.AZURE_ACR_SERVER }}/${{ env.APP_NAME }}:${{ steps.parse_input.outputs.match }}

    - name: Login to docker
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.AZURE_ACR_SERVER }}
        username: ${{ secrets.AZURE_ACR_USER_CLIENTID }}
        password: ${{ secrets.AZURE_ACR_USER_CLIENTSECRET }}

    - name: Push image
      run: docker push ${{ secrets.AZURE_ACR_SERVER }}/${{ env.APP_NAME }}:${{ github.sha }}

    - name: Push latest tag
      if: ${{ github.ref == 'refs/heads/main' }}
      run: docker push ${{ secrets.AZURE_ACR_SERVER }}/${{ env.APP_NAME }}:${{ env.LATEST_TAG }}

    - name: Push custom tag
      if: ${{ github.event_name == 'workflow_dispatch' && steps.parse_input.outputs.match != '' }}
      run: docker push ${{ secrets.AZURE_ACR_SERVER }}/${{ env.APP_NAME }}:${{ steps.parse_input.outputs.match }}
