name: Container Python

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Custom image tag'
        required: false
        default: ''
      deploy:
        description: Trigger auto deployment
        required: false
        default: '0'

  push:
    branches:
      - main
    paths:
      - src/
      - docker/*.Dockerfile

env:
  APP_NAME: abbot-skills-python
  LATEST_TAG: latest

jobs:
  container:
    runs-on: ubuntu-latest

    steps:
    - name: Parse inputs
      if: ${{ github.event_name == 'workflow_dispatch' }}
      uses: actions-ecosystem/action-regex-match@v2
      id: parse_input
      with:
        text: ${{ github.event.inputs.tag }}
        regex: '^[\w\.-]+$'
    - run: echo "CUSTOM_TAG=${{steps.parse_input.outputs.match}}" >> $GITHUB_ENV

    - name: Checkout branch
      uses: actions/checkout@v2

    - name: Login to docker
      uses: docker/login-action@v1
      with:
        registry: ${{ secrets.AZURE_ACR_SERVER }}
        username: ${{ secrets.AZURE_ACR_USER_CLIENTID }}
        password: ${{ secrets.AZURE_ACR_USER_CLIENTSECRET }}

    - name: Build image
      run: docker build -t ${{ secrets.AZURE_ACR_SERVER }}/${{ env.APP_NAME }}:${{ github.sha }} -f docker/${{ env.APP_NAME }}.Dockerfile .

    - name: Tag latest on main
      if: ${{ github.ref == 'refs/heads/main' }}
      run: docker image tag ${{ secrets.AZURE_ACR_SERVER }}/${{ env.APP_NAME }}:${{ github.sha }} ${{ secrets.AZURE_ACR_SERVER }}/${{ env.APP_NAME }}:${{ env.LATEST_TAG }}

    - name: Custom tag
      if: ${{ github.event_name == 'workflow_dispatch' && env.CUSTOM_TAG != '' }}
      run: docker image tag ${{ secrets.AZURE_ACR_SERVER }}/${{ env.APP_NAME }}:${{ github.sha }} ${{ secrets.AZURE_ACR_SERVER }}/${{ env.APP_NAME }}:${{env.CUSTOM_TAG}}

    - name: Push image
      run: docker push ${{ secrets.AZURE_ACR_SERVER }}/${{ env.APP_NAME }}:${{ github.sha }}

    - name: Push latest tag
      if: ${{ github.ref == 'refs/heads/main' }}
      run: |
        docker push ${{ secrets.AZURE_ACR_SERVER }}/${{ env.APP_NAME }}:${{ env.LATEST_TAG }}

    - name: Push custom tag
      if: ${{ github.event_name == 'workflow_dispatch' && env.CUSTOM_TAG != '' }}
      run: docker push ${{ secrets.AZURE_ACR_SERVER }}/${{ env.APP_NAME }}:${{ env.CUSTOM_TAG }}

  deploy:
    runs-on: ubuntu-latest
    needs: container
    if: ${{ (github.event_name == 'workflow_dispatch' && github.event.inputs.deploy == '1') || github.ref == 'refs/heads/main' }}

    steps:
    - name: Parse inputs
      if: ${{ github.event_name == 'workflow_dispatch' }}
      uses: actions-ecosystem/action-regex-match@v2
      id: parse_input
      with:
        text: ${{ github.event.inputs.tag }}
        regex: '^[\w\.-]+$'
    - run: echo "CUSTOM_TAG=${{steps.parse_input.outputs.match}}" >> $GITHUB_ENV

    - name: Auto deploy ${{ env.CUSTOM_TAG }}
      if: ${{ github.event.inputs.deploy == '1' && env.CUSTOM_TAG != '' }}
      env:
        GH_BOT_TOKEN: ${{ secrets.GH_BOT_TOKEN }}
      run: ./.github/deploy_fly.sh python ${{ env.CUSTOM_TAG }}

    - name: Auto deploy latest
      if: ${{ github.ref == 'refs/heads/main' }}
      env:
        GH_BOT_TOKEN: ${{ secrets.GH_BOT_TOKEN }}
      run: ./.github/deploy_fly.sh python ${{ env.LATEST_TAG }}
