name: Build and deploy Abbot to Azure - abbot

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'script/cibuild'
      - 'script/test'
      - '.github/workflows/main_abbot.yml'
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout main branch
      uses: actions/checkout@v2

    - name: Setup Python 3.7 Environment
      uses: actions/setup-python@v1
      with:
        python-version: '3.7'
    
    - name: 'Run CI Build script'
      shell: bash
      run: script/cibuild

    - name: 'Deploy abbot-skills-python'
      uses: Azure/functions-action@v1
      with:
        app-name: abbot-skills-python
        package: src
        publish-profile: ${{ secrets.AZURE_PYTHON_FUNCTIONAPP_PUBLISH_PROFILE }}
      if: github.event_name != 'pull_request'

    - name: 'Deploy abbot-skill-python-east'
      uses: Azure/functions-action@v1
      with:
        app-name: abbot-skill-python-east
        package: src
        publish-profile: ${{ secrets.AZURE_PYTHON_EAST_FUNCTIONAPP_PUBLISH_PROFILE }}
      if: github.event_name != 'pull_request'
